### ISSUE TITLE
不能搜子文件

### ISSUE THREAD

**Issue by littleforeastli** [KOHGYLW/kiftd#10]
用递归搜子文件是很简单的一个实现啊

**Comment by KOHGYLW** [comment]
目前子文件夹内容的搜索存在的主要问题为无法进行合理的显示，因为搜索结果实际上仍是本文件夹视图——不过是过滤了的。如果加入显示子文件夹内文件的功能，目前仍未找到较为“优美”的方案。实际上，区域搜索功能将来可能会在单独的页面上进行。

**Comment by KOHGYLW** [comment]
子文件搜索已加入！欢迎尝试v1.0.17版本
