### ISSUE TITLE
使用Nginx做反向代理的问题

### ISSUE THREAD

**Issue by luomucc** [KOHGYLW/kiftd#100]
我在服务器上部署了多个服务，所以用nginx做反向代理，用户通过统一端口+自定义项目名来访问，nginx配置如下：
     	location /kiftd/{ 
        proxy_pass http://172.17.0.1:82;
      } 
发现在访问的时候，静态资源加载404，原因是路径中没有/kiftd这一层，网上查资料显示配置contextpath就行了，但是我在启动脚本中加上server.context-path=/kiftd 依然不行

**Comment by KOHGYLW** [comment]
您好，确实不行。kiftd的静态资源索引默认为“/”路径，因此反向代理时也必须将kiftd映射至域名的根路径 下，不可使用子路径。当然——您可以使用多级域名区分主站和kiftd，例如，可以使用my.io作为kiftd域名，my.com作为主站域名，这样便可以保证kiftd映射在域名的根路径下。
