### ISSUE TITLE
重启服务器后怎么都没有预览了

### ISSUE THREAD

**Issue by demon200018** [KOHGYLW/kiftd#104]
系统win10 64位  最初用记事本改了系统配置文件、HOME文件， 一直都没有预览，于是删除重新解压，重新定义文件存档位置，没有更改文件，出现了原来的文件能够预览，然后更改HOME文件，发现新放入文件没有预览，以为是win10记事本编辑的原因，然后再次删除重新解压，依然没有预览，怎么弄都没有，请教此问题是哪里不对。
![image](https://user-images.githubusercontent.com/67590177/86012021-0d35c880-ba50-11ea-831f-8162385a530e.png)

**Comment by demon200018** [comment]
> 系统win10 64位最初用记事本改了系统配置文件、HOME文件， 一直都没有预览，于是删除重新解压，重新定义文件存档位置，没有更改文件，出现了原来的文件能够预览，然后更改HOME文件，发现新放入文件没有预览，以为是win10记事本编辑的原因，然后再次删除重新解压，依然没有预览，怎么弄都没有，请教此问题是哪里不对。
![QQ图片20200629213312](https://user-images.githubusercontent.com/67590177/86012198-440bde80-ba50-11ea-95f6-d41c9133a3ab.png)

**Comment by KOHGYLW** [comment]
您好，问题已收到。由于图片无法加载，因此不能确定您的情况是否只是预览按钮不显示。如果是的话，那么该问题最有可能是由于：1，无下载权限；2，文件格式不支持预览；3，浏览器缓存问题。您可以根据以上情况进行检查，若问题仍无法解决，欢迎致信kohgylw@163.com询问！
