### ISSUE TITLE
源码都没放出来也叫开源吗

### ISSUE THREAD

**Issue by littleforeastli** [KOHGYLW/kiftd#11]
源码都没放出来也叫开源吗

**Comment by KOHGYLW** [comment]
您好，考虑到解压即用版本的简洁性，其与源代码是分开存放的，本位置为其解压即用版本的存放位置。如需获取源代码，请访问：https://github.com/KOHGYLW/kiftd-source 资源库。关于源代码的路径，您在kiftd官方主页和解压即用版的README自述页面上均可找到。
