### ISSUE TITLE
求问：如何才能直接显示本身存于电脑上的文件

### ISSUE THREAD

**Issue by al90slj23** [KOHGYLW/kiftd#12]
就是不用上传，直接显示服务端电脑上指定文件夹内容

**Comment by KOHGYLW** [comment]
这个暂不支持。主要是因为kiftd使用节点信息+文件块进行存储的，所以后期会增加一个本地导入导出功能来实现此效果，请拭目以待。

**Comment by al90slj23** [comment]
好的。特来支持，有些资源一个文件夹下比较多。然后需要这样的方式分享。试过好几种。要么就是不能显示原本本地的资源。要么就是太华丽，打开资源多的文件夹就直接崩溃。
另外问下，本地资源导入是不是就要占用两倍的硬盘啊。

**Comment by KOHGYLW** [comment]
您好，感谢您的支持！

关于本地导入：是的，因为需要将文件写入kiftd的文件系统。这导致会占用2倍空间。目前的想法是：提供“导入”和“移入”两种操作，前者类似于复制，后者类似于剪切。从而让用户自行判断如何操作。

以上，希望kiftd能帮到您。

**Comment by KOHGYLW** [comment]
本地导入功能现已上线！欢迎更新并体验。
