### ISSUE TITLE
请问支持多站点吗？

### ISSUE THREAD

**Issue by jiangjiucong** [KOHGYLW/kiftd#13]
可以多站点吗？一台服务器上两个网站，部署这个后会影响其他网站的访问吗？

**Comment by KOHGYLW** [comment]
这个倒是无所谓，只需要确保：1，kiftd能够以“/”（根路径，例如http://xxx.xxx.x.x:xxxx/）访问到。2，具备独立的一个端口。即可。实际上，无论是一个物理机上部署多个网站还是多个kiftd，都确保上述两点即可。
