### ISSUE TITLE
感谢提供了这么优秀的工具，提2个小建议

### ISSUE THREAD

**Issue by jarodlee** [KOHGYLW/kiftd#134]
1、能否提供简单的log分析或查看功能？
2、能否提供根据文档内容或名称的检索功能？
3、视频的转码好像不支持rmvb的格式。。。。是版权原因吗？我在手动把很多以前的旧电影从rmvb转成mp4再上传，有点累。。。

呵呵，再次感谢！

**Comment by KOHGYLW** [comment]
您好，很高兴收到您的反馈！
1，这一建议的确不错，已经记录。
2，这一建议有待研究，尤其是考虑到性能因素，其实用性可能会在性能较差的平台上打折扣，这一问题需要解决。
3，这个格式确实比较少见，不过该功能的建议已经记录，有待未来研究。
以上，非常感谢您的建议，这是kiftd不断进步的最佳动力！

**Comment by jarodlee** [comment]
哈哈，谢谢您的回复，加油哟！
再有一个建议，能不能让目录权限可以在web上设置，比如目录的创建者可以用管理权限高的用户进行选择转移？方便文件的交流。
再报一个bug吧，应该也是编码器的原因，flv格式的视频经常出现有声音没画面的现象。视频格式确实太多了，有点为难吧，我现在都是把视频全转换成ＭＰ４之后再分享了。。。。。

**Comment by KOHGYLW** [comment]
您的建议已收到！关于转码问题已经记录，未来会进行研究。关于flac格式——考虑到该格式对于很多浏览器而言并不支持，因此，如若kiftd对其支持的话，势必也要借助服务器转码操作将其为MP3格式，再发送至浏览器播放，这样的话效果会有损失，具体效果有待未来研究。以上。

**Comment by jarodlee** [comment]
> 您的建议已收到！关于转码问题已经记录，未来会进行研究。关于flac格式——考虑到该格式对于很多浏览器而言并不支持，因此，如若kiftd对其支持的话，势必也要借助服务器转码操作将其为MP3格式，再发送至浏览器播放，这样的话效果会有损失，具体效果有待未来研究。以上。

谢谢您的解读，了解了，那就这样吧，这个反馈可以关闭了。
