### ISSUE TITLE
搜索功能能否再增加一个“全局搜索”按钮

### ISSUE THREAD

**Issue by CrazyDongjie** [KOHGYLW/kiftd#136]
当前版本的搜索功能默认是搜索当前文件夹，全局搜索需要手动输入all:关键字，操作上比较麻烦

鉴于搜索功能的常用性，建议在界面上再增加一个全局搜索的按钮

**Comment by KOHGYLW** [comment]
您好，建议已收到。实际上，这一设计也考虑过了，但是这样会让原本就不富裕的页面控件雪上加霜，因此作罢。输入all关键字是目前想到的比较好的一种方式了，暂定维持此设计。希望kiftd能够帮助到您！
