### ISSUE TITLE
一个linux与windows共用文件系统的疑问

### ISSUE THREAD

**Issue by jarodlee** [KOHGYLW/kiftd#137]
现在用win10搭了个文件分享平台，不过自己想在随身的linux笔记本上也使用相同的文件系统，不知道能不能把文件系统的文件夹复制后在linux下再启动一个kiftd直接使用呢？请告知能否通用，两个kiftd不会同时启动，只是共用文件系统。

**Comment by KOHGYLW** [comment]
您好，可以。实际上，kiftd的文件系统正是为应对此需求设计的。您可以参考《kiftd说明文档》中的【数据备份与恢复】（P65）章节操作。希望kiftd能够帮助到您！
