### ISSUE TITLE
idea启动源代码报错

### ISSUE THREAD

**Issue by 2799756** [KOHGYLW/kiftd#138]
很抱歉我对这种模式是不熟悉的,我搜索了issues发现有人跟我一样的问题,也是idea出现的问题,再不换MyEclipse的情况下如何解决?

错误：无法以UI模式输出信息，自动切换至命令模式输出。详细信息：java.lang.IllegalArgumentException: input == null!
错误！无法以图形界面模式启动kiftd，您的操作系统可能不支持图形界面。您可以尝试使用命令模式参数“-console”来启动并开始使用kiftd。

**Comment by KOHGYLW** [comment]
这可能是由于您的开发环境未能将源代码路径下某些非java源代码资源（例如程序图标等）打包至jar包中导致的——这将会令程序无法找到指定资源从而无法以图形界面的模式启动（例如IDEA等IDE在进行Maven打包时会自动忽略非java源代码的资源）。您可以修改默认的pom.xml文件并重写打包设置以确保src/main/java下所有资源都能够被正确打包至编译后的jar包中。希望kiftd能够帮助到您！

**Comment by crazyStar00** [comment]
建议pom.xml文件的build标签中添加以下配置，以避免项目以idea打开时，读不到src/java下的资源文件的问题。
````
<resources>
    <resource>
        <directory>src/main/java</directory>
        <includes>
            <include>**/*.png</include>
        </includes>
        <filtering>false</filtering>
    </resource>
</resources>
```
