### ISSUE TITLE
添加 Dockerfile 及 DockerHub 容器自动编译

### ISSUE THREAD

**Issue by wei** [KOHGYLW/kiftd#14]
感谢开源发布 kiftd。
建议可以发出官方版的 Dockerfile 并配置 DockerHub 自动发布新版本镜像。这样可以不用担心系统环境，更方便快速地运行和升级 kiftd。

**Comment by KOHGYLW** [comment]
您好，该建议已经收到。关于使用容器进行发布的建议在之前已经考虑过，不过鉴于面向的用户（例如普通使用者）大多数不了解如何配置容器，因此该功能并未上线。目前，kiftd依然会在保证安装尽可能简单的情况下提供源程序，以便于用户解压即用（虽然需要自行安装Java）。
