### ISSUE TITLE
内存释放

### ISSUE THREAD

**Issue by buqiaomuyudeheshang** [KOHGYLW/kiftd#140]
您好，我在使用软件过程中发现，刚启动时内存占用较低，但是随着操作增加，内存占用非常大，简单操作后占用1G，且长时间占用。使用内存整理软件释放后，内存占用仅几兆。本人非IT专业，请问是否可以在系统中优化一下，随时释放一下内存呢。

**Comment by KOHGYLW** [comment]
您好，1.5GB是kiftd的设计内存负载，只要不持续升高，那么就是正常的。这部分负载主要是各种预览功能使用，如果不触发这些功能，那么内存消耗就相对较低。当然，这些内存是预览功能所应该保留的，目前暂定维持原设计。以上，希望kiftd你能够帮助到您！
