### ISSUE TITLE
无法连接

### ISSUE THREAD

**Issue by Cindy-miller** [KOHGYLW/kiftd#142]
手机连接不上网盘，但是电脑可以

**Comment by KOHGYLW** [comment]
您好，该问题可能是由于手机设备与您运行kiftd的设备不在同一网段导致的，举例来说，如果您运行kiftd的设备接入了某个路由器中，那么手机就必须也接入同一个路由器的Wifi或有线网络才能链接到此kiftd，而不能使用移动网络（公网）访问。确保此条件后，手机只需像电脑一样输入正确的IP+端口号就应该可以访问了。以上，希望kiftd可以帮助到您！
