### ISSUE TITLE
更改notice.md后，仍然显示原版 的

### ISSUE THREAD

**Issue by Nixiak-nan** [KOHGYLW/kiftd#147]
第一次写A版本notice，网页能正常显示。修改成B版本后，网页能正常显示。修改成C版本后，网页仍然显示B版本，并且把.md文件删除，不会有显示，但是把.md文件加回去后，无论md文件里是什么内容，都是B版本的问题

**Comment by Nixiak-nan** [comment]
问题似乎得到了解决，我过一天后再登录网站时，已经变成C版本的内容，看样子是缓存的原因。但是前面的时间里，我尝试过清除浏览器缓存、重启进程、使用其他设备登录网站等操作，仍然没有变化。我想是不是程序内部有缓存？

**Comment by KOHGYLW** [comment]
@Nixiak-nan 很高兴看到您的问题已经解决。是的，浏览器缓存一般就是原因所在。程序本身会自动更新（延迟不会很高），这一机制无缓存。以上，希望kiftd能够帮助到您！
