### ISSUE TITLE
使用 Github Releases 发布新版本

### ISSUE THREAD

**Issue by wei** [KOHGYLW/kiftd#15]
目前编译的 jar 是直接放在仓库里。建议使用 tagging 和 Github Releases 管理和发布新版本。

https://help.github.com/articles/creating-releases/
中文：https://github.com/waylau/github-help/blob/master/Creating%20Releases%20创建发布包.md

未来推荐对开源项目免费的 TravisCI 进行自动化编译和 Release 发版。https://www.jianshu.com/p/807f8c989679

发布后将会出现在这里：https://github.com/KOHGYLW/kiftd/releases

**Comment by KOHGYLW** [comment]
非常感谢您的提示，目前已经收到。会在接下来尝试该方法。
