### ISSUE TITLE
咨询端口问题

### ISSUE THREAD

**Issue by AClatter** [KOHGYLW/kiftd#155]
除了服务端口，程序运行中还会使用那些端口呢？我想在防火墙上开放这些端口。
单文件下载使用那个端口，上传使用那个端口，打包下载又是使用那个端口？

**Comment by Nixiak-nan** [comment]
该程序只有一个端口。而且IP+端口=套接字，能唯一的识别某台服务器上某个进程，一般都只用一个端口就行了，不用那么复杂吧

**Comment by KOHGYLW** [comment]
感谢 @Nixiak-nan 的解答！如其所述，您只需开放kiftd的唯一“端口”（默认为8080）就可以使用其全部功能了。需要补充的是：如果您还启用了https协议，那么也需要开放https功能设置的端口。以上，希望可以帮助到您。

**Comment by AClatter** [comment]
感谢您的讲解



***@***.***
 
发件人： Nixiak-nan
发送时间： 2021-04-29 13:13
收件人： KOHGYLW/kiftd
抄送： AClatter; Author
主题： Re: [KOHGYLW/kiftd] 咨询端口问题 (#155)
该程序只有一个端口。而且IP+端口=套接字，能唯一的识别某台服务器上某个进程，一般都只用一个端口就行了，不用那么复杂吧

**Comment by AClatter** [comment]
大佬，我悟了，谢谢。



***@***.***
 
发件人： 青阳龙野
发送时间： 2021-05-09 22:06
收件人： KOHGYLW/kiftd
抄送： AClatter; Author
主题： Re: [KOHGYLW/kiftd] 咨询端口问题 (#155)
感谢 @Nixiak-nan 的解答！如其所述，您只需开放kiftd的唯一“端口”（默认为8080）就可以使用其全部功能了。需要补充的是：如果您还启用了https协议，那么也需要开放https功能设置的端口。以上，希望可以帮助到您。

**Comment by AClatter** [comment]
了解
