### ISSUE TITLE
我真的笑了啊

### ISSUE THREAD

**Issue by g-mph** [KOHGYLW/kiftd#169]
![image](https://user-images.githubusercontent.com/64201424/131214317-7419f960-3ac0-485a-803e-1e3289ce260a.png)

**Comment by mp075496706** [comment]
确实是够疏忽的，但不能因此否定这款软件。

**Comment by Nixiak-nan** [comment]
你笑啥？提问题之前，先看下历史issues吧
https://github.com/KOHGYLW/kiftd/issues/150
> 网盘使用shift作为多选按键，但是在win上shift是批量多选，ctrl是单独多选。有考虑将shift换成ctrl吗？这样更符合用户的习惯
> 您好，建议已收到。实际上，最初的设计的确是这样，不过，由于浏览器本身的很多快捷键也要借助ctrl，如果被kiftd占用势必会影响到这些原本的快捷键，因此才刻意将kiftd的快捷键设计为shift，从而避免冲突。当然，如您所述，这一设计的确有些“不顺手”，但鉴于目前暂未发现更好的替代方案，因此决定先维持此设计。最后，还是感谢您的宝贵建议，这是kiftd不断进步的最佳动力。

**Comment by g-mph** [comment]
> 你笑啥？提问题之前，先看下历史issues吧。一点基本的尊重都没有
> #150
> 
> > 网盘使用shift作为多选按键，但是在win上shift是批量多选，ctrl是单独多选。有考虑将shift换成ctrl吗？这样更符合用户的习惯
> 
> > 您好，建议已收到。实际上，最初的设计的确是这样，不过，由于浏览器本身的很多快捷键也要借助ctrl，如果被kiftd占用势必会影响到这些原本的快捷键，因此才刻意将kiftd的快捷键设计为shift，从而避免冲突。当然，如您所述，这一设计的确有些“不顺手”，但鉴于目前暂未发现更好的替代方案，因此决定先维持此设计。最后，还是感谢您的宝贵建议，这是kiftd不断进步的最佳动力。

你回啥？也不认真看看我圈起来的内容
根本不是一件事好吧

**Comment by hmsjy2017** [comment]
typo

**Comment by WeSourceCode** [comment]
阴阳怪气的，不用就别用，开源的还在这阴阳怪气
