### ISSUE TITLE
是否有意加入二维码功能？

### ISSUE THREAD

**Issue by OHLIA** [KOHGYLW/kiftd#17]
可以方便给手机用户下载文件，应用场景应该很多。

**Comment by KOHGYLW** [comment]
关于“扫码下载”这一功能已经收到，会在接下来研究实现方式。如果其可行性较高，则会在后续版本中加入，敬请期待！

**Comment by KOHGYLW** [comment]
您好，关于加入下载二维码的提议在近期已经研究了。不过，此实际的效果上看，操作体验并不好，尤其是使用微信扫码时不能直接下载文件这一缺陷非常影响体验，相比于直接拷贝下载链接进行下载而言优势不明显，因此该计划决定放弃。未来还会根据实际情况考虑是否重启这一计划。
