### ISSUE TITLE
使用了https后，还能反向代理吗？

### ISSUE THREAD

**Issue by Nixiak-nan** [KOHGYLW/kiftd#174]
背景描述：我现在使用8081端口作为kiftd服务器端口，域名使用kiftd.com。那么我应该请求   kiftd.com:8081  来访问kiftd网盘。当我启用https功能后，假设使用的端口是8082。那么当我 请求   http://kiftd.com:8081  ，会自动跳转到  https://kiftd.com:8082

问题：我最开始是可以用反向代理，抹去8081的端口信息。但是启用了https后，如果我使用反向代理代理8081端口，那么url地址仍会显示https://kiftd.com:8082 ，如果直接代理 8082端口，那么访问将不成功。 

我可以使用反向代理，让用户看不到8082端口号吗？

**Comment by mp075496706** [comment]
可以，去看看文档，有提到怎么做。我之前搞过，后来还是改回http了，因为速度比https更快

**Comment by Nixiak-nan** [comment]
> 

我有仔细查阅过文档，但是文档并未解决我的问题，如果方便的话，你可以帮我指出是在文档的哪一部分吗？

**Comment by Nixiak-nan** [comment]
问题已经解决。反向代理到https协议上，需要申请证书。
