### ISSUE TITLE
请问文件上传之后在哪个文件夹？

### ISSUE THREAD

**Issue by tanix12qly** [KOHGYLW/kiftd#18]
如题

**Comment by WeiMXi** [comment]
你可以看看配置文件里，不过这个是分割成文件块，不是原文件了。

**Comment by KOHGYLW** [comment]
您好，上传文件之后，如果您希望在kiftd主页上找到它，那么只需在上传时正在访问的路径下查看即可。上传文件会保存在您上传时访问的路径中。如果您希望在本地计算机上找到它，目前还无法直接这样做。不过在下一个版本会提供本地文件操作功能，能够在本地操作网盘中的文件，敬请期待。
