### ISSUE TITLE
建议：希望集成内网穿透，自动更新

### ISSUE THREAD

**Issue by yi-ge** [KOHGYLW/kiftd#189]
希望增加内网穿透的一键安装功能，点击后自动下载frp或其他内网穿透二进制并自动配置运行。希望软件本身能自动更新。都已经可视化到这个程度了，就再进一步吧~😂

**Comment by ooo-o-ooo** [comment]
借楼：
1. 建议增加P站、91、X豆视频等视频网站爬取功能
2. 建议增加出墙功能
3. 建议增加放射WiFi功能，不用运营商的网络就可以直接访问
4. 建议增加集成OSS功能
5. 建议增加同步功能
6. 建议增加聊天功能
7. 建议增加邮件功能
8. 其它建议楼下完善.............
