### ISSUE TITLE
希望作者处理同名文件上传中存在的漏洞

### ISSUE THREAD

**Issue by Creling** [KOHGYLW/kiftd#19]
目前对于同名文件的上传，有一个“覆盖”选项，这实际上是变相给出了“删除”选项，因为只要用同名空文件覆盖就好了（亲测有效），不利于数据的安全保存。
希望作者可以处理这个漏洞

**Comment by Creling** [comment]
感觉作者大大贡献了如此好用的程序

**Comment by KOHGYLW** [comment]
您好，该问题确实会导致具备“上传权限”的用户通过这种手段能够删除文件（恶意覆盖），现已开始完善方案，非常感谢您的反馈！具体升级会在后续版本中体现。

**Comment by KOHGYLW** [comment]
新版本中，越权现象已避免。仅当用户具备“删除”权限时才可进行“覆盖”，否则仅能“跳过”或“保留两者”！再次感谢您的反馈！
