### ISSUE TITLE
开启https后启动失败

### ISSUE THREAD

**Issue by lzt123123** [KOHGYLW/kiftd#199]
1.首先证书已经申请并放置在kiftd目录下
![image](https://user-images.githubusercontent.com/43226215/197701404-83633271-fb12-4496-a64b-caae949eadaa.png)
2.conf/server.properties已配置
![image](https://user-images.githubusercontent.com/43226215/197701533-ae28770e-f71f-475e-94a0-0e91578a3528.png)
3.启动报错（应该是不存在端口占用的，启动之前我已经查看过端口占用情况了）
![image](https://user-images.githubusercontent.com/43226215/197701806-f25b46ea-53f8-4327-8666-1d8bcc81a35a.png)
![image](https://user-images.githubusercontent.com/43226215/197701861-e707ad5c-84f4-47cb-89cd-f7cacee59973.png)

**Comment by UnicornUnderMoon** [comment]
@ lzt123123 c 问题怎么解决的？
