### ISSUE TITLE
视频文件在线播放黑屏，只有声音

### ISSUE THREAD

**Issue by itning** [KOHGYLW/kiftd#20]
RT。

**Comment by itning** [comment]
浏览器： Google Chrome  72.0.3626.119（正式版本） （64 位）

**Comment by KOHGYLW** [comment]
您好，这是由于该浏览器不支持被播放的视频格式造成的。各个浏览器的视频解码器均不同，例如Chrome只支持H.264格式的MP4视频，而Edge和Safari则支持H.265编码的MP4，甚至Safari还支持MOV……因此，您播放的视频可能无法被您的浏览器解码导致无图像。如果您需要将其分享给其他用户在线观看，那么最为稳妥的方案是使用转码工具将MP4格式转换为AVC（H.264）编码，再上传至kiftd中。目前主流浏览器均能解码这种类型的格式。
