### ISSUE TITLE
 建议：两个关于用户登录界面的建议

### ISSUE THREAD

**Issue by sooxin** [KOHGYLW/kiftd#21]
> 应用版本：1.0.16-RELEASE

首先感谢作者开源如此实用的软件！以下是两点关于登录界面的优化建议：

1. 请不要提供过于详细的登录错误提示信息
  当输入了不存在的账户，页面会提示"账户不存在或未设置"，当输入了正确的账户和密码的错误时，页面会提示密码错误或未设置。这样的信息过于详细，是不安全的。这样会让攻击网站的人更容易遍历出用户名和密码。

2. 建议添加图片验证码
  同样的原因，现阶段登录没有验证码，只需在浏览器控制台执行个简单的脚本，虽然会花点时间，但也是可以暴力破解出用户名和密码的。破解成本很低。
  希望能添加个简单的图片验证码，增加一些破解成本。

Thanks！

**Comment by KOHGYLW** [comment]
很高兴收到您的反馈！关于用户登录信息提示：实际上这一点是特意设计的，虽然这样确实增加了爆破的风险，不过考虑到kiftd是面向个人和团队使用（尤其是局域网内使用）场景，因此还是选择将易用放在了首位（实际上，防止爆破的最佳手段还是选用一个不容易被爆破的密码）。关于图片验证码，这个建议确实很重要，本人也考虑在登录中设计一个反爆破机制，例如在一定时间内超过多少次密码错误则需要“冷却”一定的时间才可以继续尝试。当然，具体设计还需要进一步研究，并在后续加入。

**Comment by KOHGYLW** [comment]
您好！图片验证码功能现已加入，该功能在设计时同时考虑到了使用的便捷性和安全性，当一个账户出现一次及以上的密码验证失败后，后续的登入尝试必须经过图片验证码验证。欢迎更新体验。
