### ISSUE TITLE
大文件上传失败

### ISSUE THREAD

**Issue by caly5144** [KOHGYLW/kiftd#22]
上传比较大的文件时，虽然进度条已满，却一直显示“正在上传”，等待十几分钟后关掉上传界面，文件也并没有出现在目录中。

如下图所示，我上传了kiftd的源码（81.4m），一直卡在这个界面

![image](https://user-images.githubusercontent.com/27693473/54737127-624a2400-4be9-11e9-900a-51ad431b0c6c.png)

**Comment by KOHGYLW** [comment]
您好，这一问题怀疑是由于登录凭证过期导致的——比如上传时间超过了30分钟且中途未进行任何其他操作，那么可能会导致文件上传后被权限过滤阻止，导致无法完成上传。这一问题目前已经计划改进，使得权限检查能够在上传前进行，避免上传时间过长导致的登录失效而无法通过权限检查。

**Comment by KOHGYLW** [comment]
新的上传权限检查机制已经可以避免时间过长导致的权限失效问题！欢迎升级v1.0.17体验。
