### ISSUE TITLE
100多gb的文件被清空了？

### ISSUE THREAD

**Issue by Reimenn** [KOHGYLW/kiftd#221]
我在【设置】中的文件系统路径【管理】中添加了我的数据文件夹，然后启动服务器之后就把我的文件夹清空了？

就不能加一个“这会清空文件夹”的提示？什么地方也没告诉过我这个操作会删除现有文件啊。

现在100多gb的文件没了，数据恢复回来的内容也是错的。

这个设计实在是**粗糙**！。

**Comment by KOHGYLW** [comment]
您好，反馈已收到。
您提到的“添加了我的数据文件夹”如果是指【添加】一个【新的扩展存储区】，那么正常情况下应该不会影响到已有的文件数据。如果发生了这样的情况，则证明了一个未被报告的bug，本人非常希望能通过邮件与您进一步交流该问题。
如果您【删除】了某个【扩展存储区】，则可能造成已有文件数据的丢失——在此过程中，系统会进行风险提示，并且也会提供提前移出数据的指引流程。
如果您【移动】了【主文件存储区】，则在使用新的主文件存储区后会重新建立一个新的文件系统。但是，原文件系统也并不会因此被删除。在没有扩展存储区的情况下，您只需将主文件存储区改回原存储区文件夹就可以继续使用原来的数据了。
本人推测，您遇到的问题可能是：在您设置了扩展存储区的情况下，未提前移动这些扩展存储区而直接更改了主文件系统存储路径。这种操作存在的风险虽然在《kiftd说明文档》的【管理文件系统存放路径】（P46）一节中进行了提示，但并未在系统中加入类似的警告，此设计确实存在提示不周的问题。未来，本人将会设计增加警告信息。
对此带来的不便深表歉意！
如果您遇到的问题并非上述情况，欢迎进一步反馈~

**Comment by Reimenn** [comment]
你好，我用刚刚下载的最新版本复现了一下，流程和结果录制成了视频：

https://github.com/user-attachments/assets/1d28e355-a714-44b3-815d-80a4551cadc7

事故是在家里的个人电脑上出现的，视频是在公司电脑上录制的，至少说明这个问题不是个例。

**Comment by KOHGYLW** [comment]
视频已收到。
根据您提供的过程来看，似乎您将扩展存储区理解成了能够让kiftd直接读写操作系统自身的文件系统的功能。实际上，该功能是用于给kiftd文件系统扩展存储空间的。关于kiftd文件系统的详细说明，推荐参阅《kiftd说明文档》中的【管理文件系统存放路径】（P44）一节。
由于该操作不一定会清空其中的数据（例如移动扩展存储区时），因此这一步并未设计相关的警告。
不过，此功能存在的误解风险已经被记录。未来，本人会考虑在必要位置增加额外的说明。
再次对此表示歉意！

**Comment by Reimenn** [comment]
不论如何，这里也应该加上【不能选择非空文件夹】或者【这将会清空文件夹】这种警告！

**Comment by KOHGYLW** [comment]
实际上，该操作不一定会清空文件夹，更不能只允许选择非空文件夹。例如，在需要移动扩展存储区时，里面是一定存在数据的，而且它们不会被清空。
清空机制是由于kiftd发现了存储空间中存在一些【无效】的文件块，而kiftd有时可能会出现删除文件节点成功但删除文件块失败的情况，为了避免垃圾积累，因此设计了服务器启动过程中自动校对两者的机制。如果是文件系统中存在的文件块，那么实际上并不会被删除。考虑到如果加入了【可能清空文件夹】的提示，本人担心此提示可能会造成用户的疑惑：原本这些文件块就是文件系统中的，难道会被清空？所以这里没有设计提示。
因此本人认为：该问题的最佳的解决方案还是应在必要的地点增加对文件系统功能的说明。

**Comment by Reimenn** [comment]
确实应该增加说明，但是程序内的弹窗提示肯定也是必须的，任何会删除用户数据的操作都应该加上弹窗提示。

kiftd 看起来是个很易用的工具，启动之后更是有图形界面，一般人肯定都会先在界面上到处点点尝试一下，发现自己搞不懂才会去看文档。

不能指望每个来操作软件的用户都是熟读过文档的！

**Comment by KOHGYLW** [comment]
该建议已经记录，未来会研究针对此风险增加直观的规避指引。
