### ISSUE TITLE
下载目录，其中文件缺失

### ISSUE THREAD

**Issue by CodingOX** [KOHGYLW/kiftd#24]
通过Shift+A 选择目录，下载后发现目录中的文件缺失。
比如目录A有：目录1，目录2，文件1，文件2 。
下载解压后发现只有目录1和目录2，文件1和文件2缺失。

**Comment by KOHGYLW** [comment]
该问题在测试中尚未发现过，对于打包下载而言，之前的反馈和测试中全部能够正常打包选中的文件和文件夹。您可以提供更加具体的操作过程或示例，以便于本人查找该问题所在。如果它存在，那么这也是个严重的问题。

**Comment by CodingOX** [comment]
这个是目录：
![image](https://user-images.githubusercontent.com/9800933/55924514-c1291900-5c3c-11e9-8214-afa5886ad831.png)
点进去第二层是
![image](https://user-images.githubusercontent.com/9800933/55924591-00f00080-5c3d-11e9-9246-25979c9fb5cb.png)
点击最上面的PotPlaer是这样的
![image](https://user-images.githubusercontent.com/9800933/55924607-106f4980-5c3d-11e9-8020-18543e411261.png)
然后我z在最外层，也就是第一张图片这个，通过Shift+A选择后，下载，打包之后解压是这样的
![image](https://user-images.githubusercontent.com/9800933/55924645-30067200-5c3d-11e9-91bd-49e1a40bf50f.png)

**Comment by CodingOX** [comment]
> 该问题在测试中尚未发现过，对于打包下载而言，之前的反馈和测试中全部能够正常打包选中的文件和文件夹。您可以提供更加具体的操作过程或示例，以便于本人查找该问题所在。如果它存在，那么这也是个严重的问题。

问题应该是 文件本来和目录同级，但是你把同级文件移动到了同级的新建目录中。应该是这样的，反编译看了下代码，应该是这样的！

**Comment by KOHGYLW** [comment]
好的，问题已经确认！该问题确实存在，将在下一版本中修正。再次感谢您的反馈！这是kiftd不断进步的最佳动力。

**Comment by KOHGYLW** [comment]
您提到的文件打包下载问题已于1.0.17版本修复！现可从github上获取该版本！
