### ISSUE TITLE
一些个人需求

### ISSUE THREAD

**Issue by snowjade** [KOHGYLW/kiftd#25]
你好，最近了解到这个作品 -- kiftd ，确实是非常优秀的作品。而且还是 开放所有权限的，这样就算我有一些特殊的需求，也能够自己修改定制。对于我个人来讲有如下的一些需求：
    1.简化界面，个人不是太喜欢极客感很强的界面。这个我做了一部分，网页端还没有做。
![image](https://user-images.githubusercontent.com/11959369/56114293-03cb5800-5f93-11e9-91a6-67a62484bf8b.png)
    2. 我希望它可以直接共享的我的文件夹， 而不是一定要复制一份到自带的“仓库”。比如我希望把我的一个20G电影共享出去，可以在手机和平板上播放。 也就是说我可以直接把文件拖到特定的 共享文件夹 进行共享，而不是一定要走一个上传复制的步骤。
      当我试图修改源码实现的时候，发现这个系统整个设计逻辑 是把  文件的 各种信息包括路径信息 映射存储起来，如果要修改成我要的功能，工作量有点大。
     不知道有多少人有和我有一样的需求。

**Comment by KOHGYLW** [comment]
建议已经收到！
关于界面，目前该界面在某些情况下的表现确实不尽如人意（尤其是在高分辨率下），同时表现也稍欠现代感，因此对于界面的美化后续还会继续进行。
关于共享文件夹这一需求，实际上确实可以使用一些代码实现——而且不是通过修改kiftd的代码，而是编写一些其他代码。关于这个方面的内容，可以参见这篇博文，其内容就是如何实现将指定本地文件夹内新增的文件自动导入至kiftd中：https://blog.csdn.net/qq_25670227/article/details/88863127
