### ISSUE TITLE
运行不了呀

### ISSUE THREAD

**Issue by ninggc** [KOHGYLW/kiftd#27]
root@vultr:~/kiftd# ls -l
total 34128
-rw-r--r-- 1 root root     8856 Apr 26 04:42 README.md
drwxr-xr-x 2 root root     4096 Apr 26 04:42 conf
drwxr-xr-x 3 root root     4096 Apr 26 04:42 filesystem
drwxr-xr-x 2 root root     4096 Apr 26 04:42 fonts
-rw-r--r-- 1 root root   231453 Apr 26 04:42 kiftd-1.0.18-RELEASE.jar
-rw-r--r-- 1 root root 34666399 Apr 26 04:42 kiftd????????????.pdf
drwxr-xr-x 2 root root     4096 Apr 26 04:42 libs
drwxr-xr-x 2 root root     4096 Apr 26 04:42 logs
drwxr-xr-x 3 root root     4096 Apr 26 04:42 mybatisResource
drwxr-xr-x 8 root root     4096 Apr 26 04:42 webContext
-rw-r--r-- 1 root root     1100 Apr 26 04:42 ????????????
root@vultr:~/kiftd# pwd
/root/kiftd
root@vultr:~/kiftd# java kiftd-1*
Error: Could not find or load main class kiftd-1.0.18-RELEASE.jar
root@vultr:~/kiftd#

**Comment by KOHGYLW** [comment]
您好，如果需要使用“命令模式”进行启动，那么启动命令应该是：
`java -jar {kiftd主程序所在路径}/kiftd-?.?.?-??????.jar -console`
如上将以命令模式启动kiftd，之后您可以根据提示进行操作。若仍有问题，欢迎继续询问！
