### ISSUE TITLE
长时间上传和下载会导致用户退出登录

### ISSUE THREAD

**Issue by JoeZhangYN** [KOHGYLW/kiftd#29]
版本1.0.18，系统 win server 2019 DataCenter.
长时间下载或者播放有的时候会断流。
上传，明明没有结束，但用户自动超时退出。
希望能够设置登录超时时间或者判断用户是否在操作。

**Comment by KOHGYLW** [comment]
问题已经收到。之前对于上传已经做了专门处理来避免长时间上传会导致的用户凭证失效问题，不过未在总过滤器中增加相应的处理，这可能是导致该问题的原因。接下来会寻找解决方法以避免这一问题。

**Comment by KOHGYLW** [comment]
您好！目前新版本中已经加入了自动应答机制来避免此问题，欢迎更新体验！
