### ISSUE TITLE
XSS vulnerability found via <iframe> tag when upload file

### ISSUE THREAD

**Issue by showuon** [KOHGYLW/kiftd#32]
create a file named with "<iframe src=javascript:alert(4)>.jpg", and upload this file. After that, every user with read permission will be affected.
上传一个命名为"<iframe src=javascript:alert(4)>.jpg"的文档，所有有read权限的使用者都会受影响

![image](https://user-images.githubusercontent.com/43372967/60877395-4c33a280-a270-11e9-9e3a-481231794a9d.png)
![image](https://user-images.githubusercontent.com/43372967/60877590-b8160b00-a270-11e9-990b-489389a1c59c.png)

**Comment by KOHGYLW** [comment]
Thank you for your feedback!
The testing result indicate that the problem does real exist,and it plans to be repaired in the next version.
Bug reports, fixes, and suggestions are also welcome.

**Comment by KOHGYLW** [comment]
This loophole is fixed in version 1.0.19 .
