### ISSUE TITLE
上传文档 限制太小，最大只能5M？

### ISSUE THREAD

**Issue by netyuchangfa** [KOHGYLW/kiftd#33]
上传文档 限制太小，最大只能5M？

哪里可以设置单个文件上传的大小？

**Comment by netyuchangfa** [comment]
找到了原因，，被NGINX反向代理后，上传文件不行。有问题。。。。
看来是不支持NGINX反向代理 ？

**Comment by KOHGYLW** [comment]
您好，关于这个问题之前有用户反馈过，目前的解决方案非常简单：在Nginx中存在一项规则设置，规定了最大上传文件的体积，您只需将其修改为不限制即可。
具体方法如下：
1，打开Nginx配置文件。
2，找到client_max_body_size一项。
3，将该项后方的数值修改为您希望的最大上传约束。
例如：“client_max_body_size 1000m;”代表允许最大上传体积为1000MB的单一文件。
