### ISSUE TITLE
导入文件功能

### ISSUE THREAD

**Issue by africa1207** [KOHGYLW/kiftd#34]
自定义了文件目录，但是还是需要使用导入文件，但是导入文件好像就是复制文件到文件目录，如果我有2T视频文件，那不就又要复制2T文件，硬盘就需要至少4T才行了。不能像windows一样的共享目录一样吗，把文件放在文件夹共享就行了？

**Comment by KOHGYLW** [comment]
您好。该设计的目的是为了尽可能将kiftd的文件管理规则与操作系统的分离开，便于不同操作系统之间传输文件。目前，kiftd尚无法直接将某一文件夹作为分享文件夹使用。目前虽然也有关于直接共享某一文件夹的构想，不过由于其效率较低（因为需要经常迭代检索文件，响应速度远不及存储在kiftd文件系统中快），因此尚未实现。kiftd会继续寻找较优方案以便于实现类似的功能。

**Comment by MuenYu** [comment]
@KOHGYLW 那是否可以复制后不改变源文件的名称和后缀呢？这样就可以把原件删掉节约存储空间了

**Comment by KOHGYLW** [comment]
@MuenYu 进行拷贝的目的并不是kiftd希望另存一份文件副本，而是要将其统一管理，这里统一管理的根本所在就是使用唯一码命名文件，便于增删改查，同时也避免了可能因文件名中存在特殊符号导致的系统不兼容问题（Linux与Windows对文件名的限制规则不同，如果保留原文件名则可能导致使用Linux系统的用户无法将某些文件上传至运行于Windows系统下的kiftd内）。此外，将文件存放在kiftd中是可以随时本地导出的，这与您直接存储在磁盘中的文件原版原理一致。

**Comment by yjiawqgj** [comment]
> 您好。该设计的目的是为了尽可能将kiftd的文件管理规则与操作系统的分离开，便于不同操作系统之间传输文件。目前，kiftd尚无法直接将某一文件夹作为分享文件夹使用。目前虽然也有关于直接共享某一文件夹的构想，不过由于其效率较低（因为需要经常迭代检索文件，响应速度远不及存储在kiftd文件系统中快），因此尚未实现。kiftd会继续寻找较优方案以便于实现类似的功能。

这是一个很好的建议，我也想要这样一个拥有此功能的网盘。之前试用了一下cloudreve，确实比你的网盘安装方便，但是他有两个功能没有，就是通过后台复制到网盘的目录以直接存在在网盘里而不用通过上传。还有一个是下载断点续传，为什么我要试你的网盘项目，因为我在你的项目说明上说了有下载断点续传。这就是我看你的布置复杂麻烦才值得一试的。cloudreve我试用了一下下载续传，下载暂停后，停了一分钟然后继续还能续传，我又重新试了一个文件，下载一点后，然后暂停一下午，到了晚上直接链接失效了。相比一些没有用的功能和丑陋的界面，断点续传只能维持一会一点用也没有。没有考虑网络问题。他的官网宣传的花里胡哨，强调各种，但这两个实用功能一个也没有。安装了一天就直接卸载了。
