### ISSUE TITLE
文件导入过大失败后无法删除

### ISSUE THREAD

**Issue by JoeZhangYN** [KOHGYLW/kiftd#36]
本地环境：
  Windows 10 1903 企业版 3700x 平台。
  JAVA: jdk-8u211-windows-x64
  用kiftd-1.0.19-RELEASE.jar开启服务后，点击文件，导入一个14.7GB的zip压缩包。一段时间后，提示失败，页面刷新无文件，点击删除，提示：删除文件失败，该操作已被中断，未能全部删除。然后就没然后了。

**Comment by KOHGYLW** [comment]
您好，这可能是由于删除延迟造成的。您可以尝试重启服务器，再查看待删除的文件是否仍存在。若仍存在，请再次回复。

**Comment by KOHGYLW** [comment]
您好，由于您的问题在很长时间内未得到进一步的反馈，因此将其关闭。若您的问题仍未解决，欢迎提交新的issue以便得到进一步的帮助！
