### ISSUE TITLE
下载文件名称不正确

### ISSUE THREAD

**Issue by MuenYu** [KOHGYLW/kiftd#37]
创建文件下载任务时，任务名称为`downloadFile.do`，与源文件不符

但如果使用`下载链接+`创建下载任务时，则不存在此问题

本人使用的时安卓设备，web访问时出现，复现概率：100%

**Comment by KOHGYLW** [comment]
您好，请问您是使用第三方下载器或者浏览器下载插件进行下载还是使用浏览器原生的下载方式？

**Comment by MuenYu** [comment]
@KOHGYLW 浏览器原生的下载方式

**Comment by KOHGYLW** [comment]
@MuenYu 那么您使用的浏览器类型是？

**Comment by MuenYu** [comment]
@KOHGYLW 
内核：Android webview 74
客户端：via

**Comment by KOHGYLW** [comment]
@MuenYu 问题已收到。这一浏览器内核尚未进行官方支持，因此其可能无法正确解析请求头中的下载文件名。目前，该问题可以通过使用下载链接进行下载规避，解决方案也会在接下来进行研究。
