### ISSUE TITLE
启用MySQL

### ISSUE THREAD

**Issue by xiaohu95271** [KOHGYLW/kiftd#38]
启用MySQL时，每次启动会在数据库自动建表，请问是怎么建表的呢

**Comment by KOHGYLW** [comment]
您好，键表流程遵循以下原则：服务器启动时，若数据库中不存在FOLDER和FILE表，则创建之，并将ROOT根节点文件夹写入新建的FOLDER表中，同时判别一些特殊字段是否存在（兼容旧版本），若不存在则在表中添加。若数据库中存在上述两表，则直接进行后续步骤。
