### ISSUE TITLE
下载程序解压后，运行失败

### ISSUE THREAD

**Issue by ganenyouni** [KOHGYLW/kiftd#39]
1、从github下载项目解压后，点击.jar包运行出现提示：A Java Exception has occurred。
2、路径中无中文，且所需java环境已经配置正确。
谢谢。

**Comment by KOHGYLW** [comment]
您好，能否提供具体的运行环境信息？包括操作系统、Java版本等？

**Comment by ganenyouni** [comment]
操作系统win10企业版，java1.8。
就是下载压缩包解压后直接点击的.jar，从官方主页下载的压缩包。
谢谢！！



---原始邮件---
发件人: "青阳龙野"<notifications@github.com>
发送时间: 2019年8月6日(星期二) 下午5:02
收件人: "KOHGYLW/kiftd"<kiftd@noreply.github.com>;
抄送: "Author"<author@noreply.github.com>;"ganenyouni"<xian401@qq.com>;
主题: Re: [KOHGYLW/kiftd] 下载程序解压后，运行失败 (#39)



您好，能否提供具体的运行环境信息？包括操作系统、Java版本等？

**Comment by KOHGYLW** [comment]
您的环境应该是支持运行kiftd的，能否提供一下您的kiftd主目录内容截图以及运行时出错的现象截图？

**Comment by KOHGYLW** [comment]
@ganenyouni 对了，如果您的操作系统中具备多个Java版本，或者是在无图形界面的环境下使用CMD命令模式启动，那么也请告知。该问题也可能由于这些原因引起。

**Comment by KOHGYLW** [comment]
您好，由于您的问题在很长时间内未得到进一步的询问，因此将其关闭。若您的问题未能解决，欢迎提交新的issue以便得到进一步的帮助！
