### ISSUE TITLE
能否加入文件夹上传的功能？

### ISSUE THREAD

**Issue by ChangingFond** [KOHGYLW/kiftd#40]

**Comment by KOHGYLW** [comment]
您好，这一功能即将在下一版本（v1.0.20）正式加入！目前该版本已经进入测试阶段，计划于不久后发布，敬请期待！

**Comment by KOHGYLW** [comment]
您好，新版本v1.0.20已经发布，其中包含了文件夹上传功能，欢迎下载体验！
