### ISSUE TITLE
kiftd通过代理访问时跳转到127.0.0.1

### ISSUE THREAD

**Issue by niuniudevp** [KOHGYLW/kiftd#41]
kiftd用Caddy做代理通过域名进行访问时网址会跳到127.0.0.1上去
如果将kiftd设置在域名的某个目录下，如xxx.com/abc 只能访问到xxx.com/home.html
![image](https://user-images.githubusercontent.com/46774078/63324706-2d3e2b00-c35b-11e9-9744-1d17ab2ad577.png)
![image](https://user-images.githubusercontent.com/46774078/63324768-4e9f1700-c35b-11e9-8507-f124c23bac32.png)

**Comment by KOHGYLW** [comment]
您好，kiftd在路径上要求必须使用“/”作为访问的起始路径，无法进行自定义。如果您在一个域名下包含多个网站资源，那么可以通过将kiftd设置一个不同端口的形式进行访问（例如主站资源为http://mywebsite/，那么可以将kiftd部署为http://mywebsite:8090/或其他访问端口，但不要部署为http://mywebsite/kiftd/，这样做将导致kiftd程序无法识别自己的路径）。如果该方法仍面临问题欢迎继续在下方回复。

**Comment by niuniudevp** [comment]
能添加一个配制参数吗？

**Comment by KOHGYLW** [comment]
@niuniudevp 您好，虽然对于服务器端而言添加一个参数比较简单，但是对于静态资源（例如各种html界面）来说就很难实现这一效果了。这也是为什么kiftd在设计之初便将路径固定为“/”的原因。
