### ISSUE TITLE
命令行启动后，如何退出控制台，让后台跑

### ISSUE THREAD

**Issue by duxingxia081** [KOHGYLW/kiftd#42]
命令行启动后，如何退出控制台，让后台跑

**Comment by KOHGYLW** [comment]
您好，如果您使用的是Linux系统，那么可以使用下列命令使其后台运行（直接启动服务器）：
nohup java -jar kiftd-x.x.x-xxx.jar -start & echo $!
上述命令在执行后还会打印该进程的PID号，如果您希望关闭服务器则可以使用kill命令进行关闭。
