### ISSUE TITLE
小屏幕能支持搜索吗

### ISSUE THREAD

**Issue by jht385** [KOHGYLW/kiftd#44]
在手机端或者将浏览器缩小，搜索栏会被适配得不见了，把那个form提出来感觉有点突兀，有什么快速调节的方法吗

**Comment by KOHGYLW** [comment]
您好，目前确实没有这一功能……当初设计时考虑到小屏幕的宽度可能不足以放置下所有的组件，而竖排排列太多内容又会导致用户操作不便，因此直接设计成了在小屏幕不提供搜索栏。如果您希望对其进行修改的话，可以试试取消home.js开头部分的屏幕自适应逻辑里的隐藏搜索栏逻辑。
