### ISSUE TITLE
试用后的一些建议

### ISSUE THREAD

**Issue by linpinger** [KOHGYLW/kiftd#46]
先给你点个赞，很方便的系统
有几个疑问：
1. 如果文件过多，这样全部放在一个文件夹下，会不会超过系统限制？
2. 不太清楚，文件名中的hash是文件的hash么，有考虑做个小工具，将这些文件按照数据库中的目录结构重命名，方便所有文件的备份导出？
3. 数据库有考虑做个备份么，避免数据库出现问题，导致文件目录丢失，无法恢复？

**Comment by KOHGYLW** [comment]
很高兴为您解答：
1，虽然确实有限制，但基本能够满足使用的需求。这与kiftd文件系统存储路径文件夹所在的文件系统的类型有关。例如使用FAT32的话，那么理论上每个存储区最多可以容纳6万个文件块，而如果使用NTFS的话（这也是目前Windows系统的主流文件系统），那么理论上每个存储区最多可以容纳42亿个文件块。而对于Linux系统而言，如果使用ext4文件系统，那么每个存储区理论上可以容纳无限个文件块。而且，kiftd还支持设置最多31个扩展存储区来分摊存储压力——即kiftd的理论总文件容纳量上限是所用文件系统中单文件夹容纳量的32倍。在文件数量超限之前，空闲的容量可能才是最大的限制因素。
2，不是的，那只是一个随机索引，用于kiftd快速寻址。当然，kiftd已经提供了它们的快速导出功能，详见《kiftd说明文档》中的“管理kiftd中的文件”一节。
3，目前还没有提供自动化备份。不过可以使用第2点中提到的导出功能进行手动备份，或者使用脚本或程序定时执行导出文件的操作来实现定时备份。
以上，希望能够帮助到您！

**Comment by linpinger** [comment]
感谢回复，刚才发现一个小问题，登录时，如果浏览器是IE，会跳到404页面，这个有解决办法么，虽然可以点击里面的返回主页正确显示，不过不是每台电脑都能运行"现代浏览器"的

**Comment by KOHGYLW** [comment]
@linpinger 您好，在此为您回复：
A.关于IE下跳转不正确的问题：这主要是由于IE不支持最新的定位标签而导致的，这一问题可以通过以下方法手动修正，操作很简单：
1，进入kiftd主目录，使用文本编辑器（例如记事本）打开webContext/js/login.js这个文件。
2，搜索“window.location.href”一词，定位到【window.location.href = "home.html";】一行文本。
3，在“home.html”前添加一个“/“，原行变为【window.location.href = "/home.html";】
4，保存该文件，修改完毕。
这样修改后，IE就能正确跳转了……不过，鉴于微软已经停止对IE的支持，所以为了确保kiftd的所有功能正确运行，还是推荐您优先使用一款现代浏览器进行访问。
B.目前，新建和上传的文件夹默认选中的是该目录的最大访问级别，用户可根据需要进行修改。目前，尚无该选项的锁定功能。因此，您还是要确保所有用户尽可能地熟悉该操作，从而避免误操作的情况发生（当然，文件夹的访问级别也是可以在日后进行修改的）。
