### ISSUE TITLE
PPT预览乱码

### ISSUE THREAD

**Issue by BetterLive** [KOHGYLW/kiftd#47]
如图：

![image](https://user-images.githubusercontent.com/20422532/64140138-f9243900-ce35-11e9-8b1f-fd04c4945141.png)

**Comment by KOHGYLW** [comment]
您好，这可能是由于该PPT中使用的“字体”在运行kiftd的操作系统中未安装导致的，在打开word和PPT时，kiftd需要在操作系用中寻找对应的字体来渲染它们，若找不到则会导致这些文字无法显示。要解决这一问题，您可以将该PPT中涉及到的字体安装到操作系统里或是将其字体文件拷贝至kiftd主目录内的fonts文件夹下，以便kiftd能够使用它们来渲染对应的内容。

**Comment by BetterLive** [comment]
这里对字体的命名有要求么，尝试放了微软雅黑字体到对应目录下，但是依然显示乱码

**Comment by KOHGYLW** [comment]
这个倒是没有的。只要确保字体文件中确实有对应的字体即可，如果不确定，也可以先将制作该PPT的电脑中的全部字体文件均拷贝到fonts中（需重启程序以生效）后再尝试预览，看看能否正确显示字体。

**Comment by ffegya** [comment]
作者你好 ，按照你说的方法是不行的，你最好在Windows系统下创建个ppt尝试下，我这里所有的宋体字都是乱码

**Comment by KOHGYLW** [comment]
@ffegya 您好，根据您的反馈已经进行了测试，由于此处无法展示截图，因此测试过程在贴吧中发表，内容如下：
https://tieba.baidu.com/p/6245794846

**Comment by ffegya** [comment]
建议您在Windows10系统下安装程序进行测试

**Comment by KOHGYLW** [comment]
@ffegya 您好，上述示例是为了证明在通用情况下该功能如何运作。当然，这一功能对于本身就在Windows上运行的kiftd而言也是适用的，示例如下：
![image](https://user-images.githubusercontent.com/26371200/64224321-b6339580-cf09-11e9-8a60-a3d49b599a4b.png)
![image](https://user-images.githubusercontent.com/26371200/64224344-c6e40b80-cf09-11e9-99e3-7ee2fc0121d1.png)
![image](https://user-images.githubusercontent.com/26371200/64224371-d3686400-cf09-11e9-9e5e-5664b58e2a7f.png)
也就是说，只要确保操作系统内安装了该字体，或者在kiftd主程序下的fonts文件夹内能够找到对应字体的文件，那么kiftd即可正确渲染了，

**Comment by ffegya** [comment]
您好，我已经将新的测试文件通过邮件向您回复，请您重新测试

**Comment by KOHGYLW** [comment]
@ffegya 邮件已回复。

**Comment by BetterLive** [comment]
多种字体测试了一下（PPT创建用的是Mac，程序运行在Ubuntu系统），目前只要中文，就会乱码；
推测是itext做PPT转PDF时的问题；

**Comment by KOHGYLW** [comment]
@BetterLive 如果是将kiftd安装在Ubuntu的话，那么不安装额外的字体文件确实无法显示大多数中文Office字体，因为Ubuntu仅提供文泉驿一种中文字体。itext仅提供渲染功能，但不提供字体，所有字体还是要从操作系统中获取（kiftd也无法提供字体，因为大多数字体都是受版权保护的）。
您可以尝试这样做：将编写PPT的Mac OS X系统中的/Library/Fonts/和/System/Library/Fonts/中所有字体文件（包括ttc和ttf格式）全部拷贝至Ubuntu中的kiftd的fonts文件夹内，之重启应用再尝试预览PPT。

**Comment by KOHGYLW** [comment]
@BetterLive 同理，如果PPT来自于一个Windows系统，那么就要将C:\Windows\Fonts中的所有字体文件拷贝至运行于Ubuntu的kiftd主目录下的fonts文件夹内，从而令系统能够渲染这一字体。

**Comment by BetterLive** [comment]
目前是按照你说的，将两个目录下的字体都拷贝进去了，也重启程序了，但是中文还是乱码，感觉像是路径问题

**Comment by KOHGYLW** [comment]
@BetterLive 那您可以试试进入kiftd主目录下的fonts文件夹，在确认字体文件都已经拷入后在该文件夹下执行mkfontscale和mkfontdir命令，然后再重启程序并预览PPT。

**Comment by KOHGYLW** [comment]
@BetterLive 在您尝试后还望将该方法是否奏效进行反馈，以便本人在后续用户遇到同样的问题时能够提供参考方案。

**Comment by BetterLive** [comment]
![image](https://user-images.githubusercontent.com/20422532/64241908-2c022600-cf37-11e9-9eb8-be0f91aa93a3.png)


确认有的字体微软雅黑进行测试，在/fonts下执行了mkfontscale和mkfontdir命令，重启了程序，但是没解决

**Comment by ffegya** [comment]
我认为，应该是windows系统中，某些字体不能显示出来某些汉字导致

**Comment by ffegya** [comment]
比如，我把一个中文字的字体改为Times New Roman，虽然在office中显示仍然是宋体，但是其实此时预览的话会出现乱码

**Comment by ffegya** [comment]
通过解压docx文件，可以发现，改为Times New Roman字体的汉字，其字体确实变为了Times New Roman，但是，在office中还显示为宋体，我认为，这可能是windows下office的一个bug

**Comment by BetterLive** [comment]
这么说的话，应该Office软件都存在这样的问题，所以，默认字体是不是改成宋体会比较好呢

**Comment by ffegya** [comment]
作者给出的回答是电脑中没有安装此字体，第一，我认为这不可能，因为我用的是windows系统，不可能没有宋体，而且，如果不把汉字的字体改为Times New Roman，是显示正常的

**Comment by ffegya** [comment]
仅仅是把汉字的字体改为不支持类型的字体（如Times New Roman），这时，虽然office界面上还显示为宋体，但已经不正常了，这时候预览会出错

**Comment by ffegya** [comment]
我觉得您说的有道理，不过，我还发现，把汉字字体改为不支持类型的字体时，乱码的显示效果随着改的不支持类型的字体的变化而变化，说明，程序本身还是解析了字体，只不过，该字体不支持，所以显示乱码，这也就能解释，为什么都是乱码还显示得不一样

**Comment by ffegya** [comment]
像这样，都是乱码但显示效果不同
![2019-09-04_172531](https://user-images.githubusercontent.com/54857616/64242966-14c43800-cf39-11e9-8ed3-8407a893b8bd.png)

**Comment by ffegya** [comment]
您可以在Windows下测试测试，我感觉应该是解析ppt的插件有bug

**Comment by ffegya** [comment]
我原来以为是电脑上的office 2010出现问题，可是我刚重新安装了2016，问题依旧

**Comment by BetterLive** [comment]
归根结底，是 getAvailableFontFamilyNames() 读取到的字体并没有包含实际使用的字体导致的：

![image](https://user-images.githubusercontent.com/20422532/64244056-f8c19600-cf3a-11e9-92a0-8bf89a6de94b.png)

**Comment by KOHGYLW** [comment]
@ffegya 在Windows 10上进行了测试，在您提供的PPT中，“基础”二字使用的是一种名为“Calibri”的字体，它在PPT中打开显示正常：
![image](https://user-images.githubusercontent.com/26371200/64244385-88ffdb00-cf3b-11e9-9c6e-6121285ea067.png)
但是由于不同操作系统对该字体的识别方法不同，因此kiftd不能保证用其渲染一定正确（这也就导致了某些字体可能在Mac OS X下可以使用，而在Windows下无法使用）：
![image](https://user-images.githubusercontent.com/26371200/64244823-4be81880-cf3c-11e9-9718-88a11b05e814.png)
这种问题kiftd本身无法处理，能够避免的唯一方法就是将其替换为一个各个操作系统通用的字体，例如更改为”宋体“：
![image](https://user-images.githubusercontent.com/26371200/64244923-8487f200-cf3c-11e9-83a5-28630004870f.png)
这样就能确保kiftd正确渲染这些内容了：
![image](https://user-images.githubusercontent.com/26371200/64244990-a41f1a80-cf3c-11e9-97c0-40ef86567821.png)
以上。

**Comment by KOHGYLW** [comment]
@BetterLive 是的，只要kiftd能够读取到PPT或Word中的字体，那么就一定能正确渲染它。

**Comment by BetterLive** [comment]
未来是不是可以试试其他预览方式，比如：

https://www.jianshu.com/p/2f39de746900

**Comment by KOHGYLW** [comment]
@BetterLive 目前kiftd对所有主流的Office预览功能实现均进行过研究，而您提到的调用在线预览接口的方法便是其中之一。不过，这一方案必须在联网时可用，而kiftd则需要确保在不接入外网的局域网内也能使用所有功能，因此这一方案就被放弃了。

**Comment by ffegya** [comment]
您好，我认为您说的不正确，因为calibri字体不能显示中文，所以微软office把这种不能显示为中文的字体全部处理为更改之前的字体（就是改成calibri之前的字体），在mac os下，poi也能像微软office一样处理此过程，但在Windows下确不可以，而是硬生生地还是用不支持的字体显示，所以造成了乱码。我认为这是poi的一个bug，希望您能通过修改程度，判断字体是否支持中文来解决这个问题

**Comment by ffegya** [comment]
另外，这个问题只出现在ppt，word是没有这个问题的，您可以测试下

**Comment by ffegya** [comment]
而且 ，不仅是改为calibri会出现这个问题，你把它改为Times new roman也会出现

**Comment by ffegya** [comment]
只要是不支持中文的字体都会出现这种问题（ppt)

**Comment by ffegya** [comment]
您说的方法是改为各个操作系统都能支持的字体，如宋体，我认为您没有明白问题的本质。Times new roman和calibri字体在macos 和windows上都是支持的，只是他们不支持中文而已，所以应该是将不能支持中文的字体改为能支持中文的字体，进一步讲，可以像微软office那样，将不能支持中文的字体改为上一次修改的能支持中文的字体。这样是最好的

**Comment by ffegya** [comment]
我在网上看到了poi的这个bug,之前有人像poi提交，但poi认为这是jvm字体加载的问题。

**Comment by ffegya** [comment]
我对于java仅仅了解皮毛，不太清楚背后的jvm具体运行机制，所以无法进一步分析

**Comment by KOHGYLW** [comment]
@ffegya 本质上是这样的，字体不支持该文字内容也会导致渲染失败。不过，对于由字体特性本身导致的问题kiftd不考虑进行修正，这是因为各种预览功能的本意在于显示这个文件“原始的”内容而非去猜测它“正确的”内容，这也不是kiftd预览功能的初衷。

**Comment by ffegya** [comment]
我不清楚，是否可以用poi读到上一次修改的字体，如果实在不能读到，那么用simsun代替也是个很好的选择

**Comment by ffegya** [comment]
但是，有个问题，目前很多ppt，如老师们的课件，上有很多这样的问题，用一个不支持的字体来显示中文字体，但是office上显示是没有问题的，因为office处理了这一点，如果您不在kiftd中处理的话，会导致显示十分糟糕

**Comment by ffegya** [comment]
因为，很多人用kiftd，上面上传的ppt不都是自己制作的，很大一部分来源于网络

**Comment by ffegya** [comment]
所以我认为，kiftd应该提高兼容性，可以做一个设置开关，让用户选择是否开启这个功能

**Comment by KOHGYLW** [comment]
@ffegya 您的建议已经记录，会作为后续升级的参考。不过，该方案的技术可行性以及其合理性仍待进一步研究。

**Comment by ffegya** [comment]
更重要的是，对于office2016版本以下的office，选中眼科学基础中的基础二字时，根本不会显示calibri，而是，宋体，你可以安装试下，

**Comment by ffegya** [comment]
所以，很多人，并不会意识到是字体出了问题，

**Comment by ffegya** [comment]
这会给用户带来很多麻烦，

**Comment by ffegya** [comment]
在office 365中，微软将这个问题修正了，所以才显示为calibri

**Comment by ffegya** [comment]
谢谢您采纳建议

**Comment by KOHGYLW** [comment]
@ffegya 后续升级中会参考这一建议，但并不能保证一定会加入这一功能。字体特性导致的渲染失败问题本质上仍是文件本身内容导致的问题，修改它们的预览效果可能会误导用户造成不必要的麻烦（对于一些对格式敏感的用户而言，“优化”的显示可能比直接显示无法渲染的效果更加不方便）。作为推荐的解决方案，应该使用一款专业的编辑工具打开这些文件，在线预览仅仅是提供一个快速查看功能而非作为生产工具使用，这一点kiftd是难以做到像微软提供的Office套件一样强大的。

**Comment by KOHGYLW** [comment]
@ffegya 您好，经过初步研究，由于在技术上暂缺乏程序自动识别某种字体是否能显示某种内容的方法，且了实现为与POI解析标准的统一效果，因此决定放弃在预览功能中加入自动替换字体功能的计划。未来仍将继续采用POI提供的默认转化规则作为kiftd的预览标准，直至POI本身对该问题进行升级或优化。作为官方推荐的解决方案，推荐用户：1，避免使用非中文字体编辑中文；2，将预览错误的文件下载到本地后使用标准编辑器打开，来解决这一问题。如果该功能无法满足您的使用需求，可前往： https://github.com/KOHGYLW/kiftd-source 获取kiftd源代码并重构kohgylw.kiftd.server.util. PowerPoint2PDFUtil类中的PPT转化方法来实现您希望具备的功能。kiftd一直鼓励用户对原始代码进行调整来满足自己的需求。以上，希望kiftd能够帮助到您。

**Comment by BetterLive** [comment]
多谢作者

**Comment by KOHGYLW** [comment]
@BetterLive 不客气，为每一位用户提供详细的解答是kiftd的本职所在！
