### ISSUE TITLE
怎么没看到哪里有预览按钮

### ISSUE THREAD

**Issue by tianxia0079** [KOHGYLW/kiftd#48]
请问预览按钮怎么才可以看到
用的最新版本，admin和新建账号都看不到预览按钮

**Comment by KOHGYLW** [comment]
您好，提供预览的文件均会在文件列的后方提供预览按钮，位置如图所示：
![image](https://user-images.githubusercontent.com/26371200/64224227-51783b00-cf09-11e9-9013-987fc9049c74.png)
若无此按钮，可能是由于：1，该文件类型暂不支持预览；2，无该文件的下载权限，导致的。

**Comment by tianxia0079** [comment]
doc文件也不支持预览吗

**Comment by KOHGYLW** [comment]
@tianxia0079 您好，是的。目前尚未找到合适的doc格式解析技术，因此暂无法预览doc文档，仅提供新版本的docx格式预览。
