### ISSUE TITLE
建议强强联手，整合kkfileview处理文件预览

### ISSUE THREAD

**Issue by tianxia0079** [KOHGYLW/kiftd#49]
https://gitee.com/kekingcn/file-online-preview

项目特性
支持word excel ppt，pdf等办公文档
支持txt,java,php,py,md,js,css等所有纯文本
支持zip,rar,jar,tar,gzip等压缩包
支持jpg，jpeg，png，gif等图片预览（翻转，缩放，镜像）
支持mp3，mp4，flv等多媒体文件预览
使用spring boot开发，预览服务搭建部署非常简便
rest接口提供服务，跨平台特性(java,php,python,go,php，....)都支持，应用接入简单方便
支持普通http/https文件下载url、http/https文件下载流url、ftp下载url等多种预览源
提供zip，tar.gz发行包，提供一键启动脚本和丰富的配置项，方便部署使用
提供Docker镜像发行包，方便在容器环境部署
抽象预览服务接口，方便二次开发，非常方便添加其他类型文件预览支持
最最重要Apache协议开源，代码pull下来想干嘛就干嘛

**Comment by KOHGYLW** [comment]
您好，这一项目在之前已经作为预览实现的方案进行过研究。不过，由于该项目的底层是基于OpenOffice/LibreOffice实现Office预览的，无法实现完全跨平台跨平台的特性（针对不同的操作系统无法做到开箱即用，需额外安装这些程序），而且对于kiftd而言，直接嵌入OpenOffice/LibreOffice程序实现预览功能有些“庞大”，因此这一方案也就被放弃了。考虑到kiftd的开发目标和主要应用场景，未来kiftd在增加新功能时会考虑 跨平台（尽量由纯java实现）、开源免费 和 精简（软件总体积不超过200MB，单个程序文件体积不超过100MB）三个必要前提。

**Comment by KOHGYLW** [comment]
虽然进行代码嵌入比较难，不过该工具确实很强大，因此未来可能会考虑提供一个整合接口，方便用户在安装了该工具后将kiftd内部的额预览功能切换为使用该工具提供的预览功能。

**Comment by tianxia0079** [comment]
了解！看好你哦！
