### ISSUE TITLE
外链能保持一直有效吗？

### ISSUE THREAD

**Issue by xthsun** [KOHGYLW/kiftd#50]
分享的外链能保持一直有效吗？因为特殊需要外链需要保持一直有效。
现在的方式是重启kiftd后 外链下载就自动失效了。

**Comment by KOHGYLW** [comment]
您好，直接点击下载确认对话框中的开始下载按钮，然后在浏览器的下载窗口获得该下载链接——这一链接既是永久有效的：
![image](https://user-images.githubusercontent.com/26371200/64496730-e056d000-d2da-11e9-8bec-0397331772f3.png)
![image](https://user-images.githubusercontent.com/26371200/64496764-1300c880-d2db-11e9-8ea3-c1daea245002.png)
