### ISSUE TITLE
KIFT无法启动，请检查设置或查看异常信息。

### ISSUE THREAD

**Issue by 1mmorta1** [KOHGYLW/kiftd#59]
无法使用，是哪里的设置问题吗。

**Comment by KOHGYLW** [comment]
您好，请检查kiftd输出栏中的提示信息——你可能需要向前翻阅才能看到相应的提示。一般而言，该现象可能是由于：1，端口号已被占用（可以尝试在设置中换用其他端口）；2，同时开启了多个kiftd相同的kiftd（可以尝试关闭重复开启的kiftd）导致的。
您也可以将提示信息的完整内容发送至此以帮助您排查问题。

**Comment by Wiiesen** [comment]
你好，KIFT无法启动，请检查设置或查看异常信息。
但是在前面没看到异常代码

**Comment by KOHGYLW** [comment]
> 

能否提供一下截图或者“输出内容”的全文拷贝？

**Comment by LJYYY666** [comment]
如下：org.springframework.context.ApplicationContextException: Failed to start bean 'webServerStartStop'; nested exception is org.springframework.boot.web.server.PortInUseException: Port 1024 is already in use

**Comment by KOHGYLW** [comment]
@LJYYY666 
该问题应该是由于您设置的端口已经被其他应用占用导致的，您可以换用另一个端口，或者将占用此端口的程序终止。
