### ISSUE TITLE
一使用修改密码，所有用户就都被删除了

### ISSUE THREAD

**Issue by xy-233** [KOHGYLW/kiftd#60]
一使用修改密码功能，account.properties文件就会变成0kb的空文件

**Comment by KOHGYLW** [comment]
您好，请您提供关于该问题的更多细节——例如您的运行环境、kiftd所在文件夹的权限、是否有特殊设置、问题发生时是否有错误提示等。这对于查找该问题的原因非常重要。本人将会根据上述信息尝试重现该问题并进行修复。
如果该问题是由于程序设计失误导致的，那么这将是个很严重的bug，会立即修复。

**Comment by xy-233** [comment]
运行环境 阿里云 Ubuntu 18.04.3 LTS (GNU/Linux 4.15.0-62-generic x86_64)
权限如图
![image](https://user-images.githubusercontent.com/42868492/66988300-df446a00-f0f4-11e9-818e-16bb74a4e130.png)
设置如图
![image](https://user-images.githubusercontent.com/42868492/66988438-16b31680-f0f5-11e9-907b-5459f0d787c1.png)
用了修改密码功能，会像平常一样显示账户配置更新完成，已加载最新配置，但account.properties会变空，账户全部消失，无论用哪个账户都会发生。

**Comment by KOHGYLW** [comment]
好的。目前怀疑可能是由于权限问题导致kiftd写入文件时失败，不过具体原因还需要根据程序的提示信息判断。在用户修改密码时，程序是否有错误的提示信息（位于终端/程序界面上的“输出信息”栏）？如果有的话，可以将其内容发送至此以帮助您解决问题。

**Comment by xy-233** [comment]
![image](https://user-images.githubusercontent.com/42868492/67082099-07060180-f1cb-11e9-9665-878adfb26be9.png)
终端没有错误提示。

**Comment by KOHGYLW** [comment]
没关系，能否提供一下问题发生时的日志文件？它位于kiftd主目录下的logs文件夹内，是以日期命名的，后缀为“.klog”。这是个文本文件，您可以使用文本编辑器打开它并找到问题发生日期的日志，当然，您也可以将其中的敏感信息去除后发送至本人的邮箱中以便进一步排查问题所在。
除此以外，您也可以尝试把kiftd主目录权限中的“包含子目录(l)”一项勾上（因为conf文件夹是kiftd主目录下的子目录），然后再测试一下问题是否依旧存在，如果依旧存在，也可以试试将“其它”中的“写入”权限暂时赋予。

**Comment by xy-233** [comment]
![image](https://user-images.githubusercontent.com/42868492/67087544-b47e1280-f1d5-11e9-85f4-794777b68d33.png)
日志里是这样的，
刚刚把整个文件夹包括所有子目录权限都设为777也不行

**Comment by KOHGYLW** [comment]
额……这个日志是修改密码的操作日志。在它的附近是否有异常日志？也就是TYPE为Exception类型的日志？如有，可以将其发送至此。
权限更改后也无法解决该问题的话基本可以排除权限导致该问题的可能了，在kiftd运行的同时是否可能存在另一个kiftd同时运行（例如开机自启动的）或者有文件级别的防火墙？

**Comment by xy-233** [comment]
没有TYPE为Exception类型的日志，服务器里面只装过一个kift，其他的只装了apache和宝塔面板。

**Comment by KOHGYLW** [comment]
那这就是个疑难问题了，目前的开发环境测试中尚未能成功复现该问题，而且从代码逻辑上说，如果是程序写入时出现问题应该是会留下错误日志的。该问题仍将持续关注，后期还会进行更多的测试，如有任何进展将会及时告知您。同时，如果您对该问题有任何发现，也欢迎及时反馈！

**Comment by KOHGYLW** [comment]
@xy-233 您好，您反馈的修改密码会导致账户配置文件清空的问题目前仍在尝试复现中，但并未成功。因此需要您提供一些更加具体的说明，例如您使用的操作系统、安装kiftd的详细步骤、引发问题的操作流程，如果方便的话，您也可以提供一份会导致问题出现的账户配置文件原本（即引发该问题前的账户配置文件），这对于重现该问题并查找原因至关重要，线索越详细则复现的概率越大！期待您的进一步回复。

**Comment by xy-233** [comment]
系统是阿里云UBUNTU，kift是解压tar.gz文件后直接运行，用任意账号进行修改密码都会出现账户被清空的情况，而且并不会出现异常的日志，配置文件我稍后通过邮箱发送给你，

**Comment by KOHGYLW** [comment]
@xy-233 您好，根据您提供的示例账户配置文件，本人已经在v1.0.26版本中进行了测试，但是仍未能复现该问题，基本排除了由于配置文件中存在特殊字符导致该问题的可能性。之前在v1.0.25版本中，设置文件的读写均使用了文件锁进行保护，但是由于设计上的问题已经在v1.0.26中重写了这一机制，因此您也可以升级至v1.0.26后再次测试该问题是否仍然存在。本人还会继续关注这一问题！

**Comment by xy-233** [comment]
v1.0.26版本没有这个问题了，非常感谢
