### ISSUE TITLE
是否有大图标功能

### ISSUE THREAD

**Issue by blizzjp** [KOHGYLW/kiftd#61]
在大量照片文件中寻找时如果有大图标预览功能就方便很多了

**Comment by blizzjp** [comment]
另外，解码速度太慢了，根本无法把已有的视频库导入。。。

**Comment by KOHGYLW** [comment]
目前暂无大图标功能。这主要是考虑到kiftd的响应速度，毕竟加载图标也是需要耗时的，因此选用了纯文字列表显示的风格来加快响应速度——作为补充，提供了全文件夹内的图片预览功能。
解码速度已经被很多用户吐槽过了，不过鉴于目前只能使用ffmepg引擎做解码操作，而且视频解码也是非常消耗资源的操作，因此暂时也没有更好的优化方案——当然，kiftd还会继续寻找的。
