### ISSUE TITLE
源代码的修改和运行

### ISSUE THREAD

**Issue by zaw929** [KOHGYLW/kiftd#62]
源代码下载 下来是一个jar包，把jar包反编译之后，导出放进文件夹中。但是依旧很多的地方报错，不知道从哪里修改起！所以，如何修改源码，并以springboot的项目运行。而不是双击jar包运行

**Comment by KOHGYLW** [comment]
您好，您应该是希望获得整个kiftd的原始项目资源。您可以访问kiftd的源代码仓库：https://github.com/KOHGYLW/kiftd-source
来clone其所有源代码——它也是一个使用Eclipse构建的Maven项目，如果您也使用了Eclipse作为IDE，那么您将clone下来的文件夹直接作为项目导入就可以开始使用了。
