### ISSUE TITLE
win10系统无法启动图形界面

### ISSUE THREAD

**Issue by zaw929** [KOHGYLW/kiftd#63]
错误！无法以图形界面模式启动kiftd，您的操作系统可能不支持图形界面。您可以尝试使用命令模式参数“-console”来启动并开始使用kiftd。

java.lang.IllegalArgumentException: input == null!

**Comment by KOHGYLW** [comment]
您的程序是直接从发行版下载的还是使用源代码自行编译的？

**Comment by KOHGYLW** [comment]
您的相同问题已经在源代码资源仓库的issue中进行回复。
