### ISSUE TITLE
可否添加windows后台自启动机制

### ISSUE THREAD

**Issue by tianxia0079** [KOHGYLW/kiftd#64]
可否添加windows后台自启动机制
1.提供war包版本，自行配置tomcat自启动
2.输出执行程序，内部支持

**Comment by KOHGYLW** [comment]
您好，目前kiftd已经提供了适用于各种操作系统的自动启动机制。例如可以通过如下方法实现在windows系统上的开机自启动：
https://blog.csdn.net/qq_25670227/article/details/89354944
由于kiftd中的很多设计和功能都是基于springboot整合的，如果改为war包的形式势必会删除很多功能，而且改动也比较大，因此目前暂无提供war包格式的计划。当然，kiftd的核心功能都是使用spring MVC框架实现的，因此您可以根据源代码和自身需求将其修改为一个动态web项目并打包为war格式在tomcat中运行，这也是官方鼓励的做法。
输出执行程序这一提议是指提供EXE格式的可执行程序么？提供jar格式的程序主要是为了实现各个操作系统的跨平台（EXE程序只能在Windows上运行），因此无需再额外提供EXE形式的程序。您可以将kiftd发行版运行在任意一种系统上，只要上面安装了JAVA环境。

**Comment by tianxia0079** [comment]
楼上的方案也不错！nice
