### ISSUE TITLE
java 调 ffmpeg 在特制操作系统上表现不太行啊。。。能不能出个功能调用外部的 ffmpeg?

### ISSUE THREAD

**Issue by nightmorning0** [KOHGYLW/kiftd#65]
java 调 ffmpeg 在特制操作系统上表现不太行啊。。。能不能出个功能调用外部的 ffmpeg? 我自己装一个 ffmpeg行不？
用树莓派，无论官方 arm 架构的系统还是定制版 aarch64 ubuntu 都不能在线播放，console 报错：
ERROR 650 --- [p-nio-80-exec-6] ws.schild.jave.FFMPEGExecutor            : Could not find ffmpeg executable for native/ffmpeg-aarch64 is the correct platform jar included?
或者：
ERROR 650 --- [p-nio-80-exec-6] ws.schild.jave.FFMPEGExecutor            : Could not find ffmpeg executable for native/ffmpeg-arm is the correct platform jar included?

**Comment by KOHGYLW** [comment]
您好，这一问题已经收到。关于该问题的解决方案还需要进一步研究，以适应不同的操作系统。

**Comment by KOHGYLW** [comment]
您好，该问题已经有了一个解决方案，请您测试一下是否有效：
1，准备好对应平台的ffmpeg可执行文件，例如ARM版本。
2，进入kiftd的主目录的lib文件夹中，在其中创建一个名为“native”的文件夹，确保其具备可执行权限，然后将您的ffmpeg可执行文件拷贝进去。
3，根据您的平台重新命名native文件夹内的ffmpeg文件，例如ARM版本应该命名为“ffmpeg-arm”；aarch64版本应该命名为“ffmpeg-aarch64”
4，启动kiftd并尝试视频转码功能。
如果该方法有效，请您将结果反馈于此，以便未来为更多遇到类似问题的用户提供参考方案！期待您的反馈。

**Comment by KOHGYLW** [comment]
您好，这一功能已经加入！现在，您可以使用特定操作系统的ffmpeg可执行文件替换kiftd内置的ffmpeg从而确保“在线转码”功能可用了。具体操作方法请参阅新版本的《kiftd说明文档》。
