### ISSUE TITLE
有的gif图片上传之后，显示不正常

### ISSUE THREAD

**Issue by xjfnet** [KOHGYLW/kiftd#67]
有的gif图片上传之后，显示不正常
看上去像是变成了256色，而且不会动了
本地查看正常，本地直接拖到浏览器上也正常
上传的时候有转换吗？是不是转换出问题了？

**Comment by KOHGYLW** [comment]
您好，这一现象是由于kiftd在提供预览图片服务时，为了能够在网络带宽有限的情况下仍能为用户提供较好的体验，因此会将大于2 MB的图片文件进行压缩，并统一转化为jpg格式（如果是gif动态图，那么将仅保留第一帧图像）。这一处理仅会对图片预览生效而不会改变kiftd中存储的原始图像，因此，对于这类体积超过2 MB的gif动态图片，如果您仍希望浏览动态效果，可以选择将其下载下来后在本地进行查看。
