### ISSUE TITLE
能否增加一个url前缀

### ISSUE THREAD

**Issue by siccs** [KOHGYLW/kiftd#68]
# 环境
- 我想用 nginx 反代 kiftd，但是 localtion / 已经被其他服务(ReadTheDocs) 占用了

# 需求
- kiftd 的 url 能否增加一个统一前缀(kiftd)，类似如下
    - http://127.0.0.1/ **kiftd** /home.html
    - http://127.0.0.1/ **kiftd** /pdfview/web

**Comment by KOHGYLW** [comment]
您好，在反向代理环境下，您也可以尝试手动修改kiftd的URL前缀，方法是：进入kiftd主目录，进入其中的webContext文件夹，对其中的home.html、prv文件夹内的四个HTML文件、quickview/video.html共计6个HTML进行如下操作：使用文本编辑器打开它们，搜索并找到其中的“<base href="/">”部分（它们一般位于文件的头几行），将其中的“/”修改为其它URL路径，例如“<base href="/kiftd/">”。这样便可以修改kiftd的访问路径了。
除此以外，将kiftd设置为与主站不同的端口号以便区分它们的URL也是官方推荐的做法，例如访问主站：“http://127.0.0.1/”，访问kiftd："http://127.0.0.1:9000/"。
以上，希望能够帮助到您！

**Comment by KOHGYLW** [comment]
您好，经过研究，目前认为：在使用反向代理的情况下，并不需要单独为kiftd增加URL前缀修改的功能——这是由于主流反向代理服务器都是支持将不同端口的服务映射到不同路径下的。举例来说，如果您的主页项目运行于 http://127.0.0.1/ 上（即80端口的根路径），kiftd运行于 http://127.0.0.1:9000/ 上，那么可以通过反向代理设置将您域名的“/”映射至 http://127.0.0.1/ ，再将您域名的“/kiftd/”映射至 http://127.0.0.1:9000/ ，这样当用户访问 http://您的域名/ 时，请求将会被转发主页项目 http://127.0.0.1/ 上，而当用户访问 http://您的域名/kiftd/ 时，请求将会被转发至kiftd项目 http://127.0.0.1:9000/ 上。要了解相关的反向代理设置方法，可以参考您使用的反向代理服务器的说明文档，以上。

**Comment by KOHGYLW** [comment]
之前的回复有误，已经进行了更新！您可以尝试新回复中提到的方法解决这一问题，希望能够帮助到您。

**Comment by hwiechern** [comment]
> 

这样的修改还有效吗？域名资源有限，无法通过绑定不同域名实现（包括二级域名）。

**Comment by hwiechern** [comment]
> >您好，在反向代理环境下，您也可以尝试手动修改kiftd的URL前缀，方法是：进入kiftd主目录，进入其中的webContext文件夹，对其中的home.html、prv文件夹内的四个HTML文件、quickview/video.html共计6个HTML进行如下操作：使用文本编辑器打开它们，搜索并找到其中的“<base href="/">”部分（它们一般位于文件的头几行），将其中的“/”修改为其它URL路径，例如“<base href="/kiftd/">”。这样便可以修改kiftd的访问路径了。
除此以外，将kiftd设置为与主站不同的端口号以便区分它们的URL也是官方推荐的做法，例如访问主站： "http://127.0.0.1/" （80端口），访问kiftd： "http://127.0.0.1:9000/" （9000端口）。
以上，希望能够帮助到您！
> 
> 这样的修改还有效吗？域名资源有限，无法通过绑定不同域名实现（包括二级域名）。

经过测试，大部分功能是可以的，目前只遇到登录成功后跳转的问题，推荐作者将这个写进配置选项。

**Comment by hwiechern** [comment]
> 经过测试，大部分功能是可以的，目前只遇到登录成功后跳转的问题，推荐作者将这个写进配置选项。

/webContext/js/login.js第98行，在"home.html"前添加前缀即可实现登录跳转，登出、注册等其他情况类似处理。
