### ISSUE TITLE
kiftd-1.0.26-RELEASE.jar启动无法找到主类

### ISSUE THREAD

**Issue by dengyoujun** [KOHGYLW/kiftd#70]
启动jar包找不到main方法，，

**Comment by KOHGYLW** [comment]
这可能是由于操作系统启动jar包的方式不正确（或无法识别jar格式的程序）造成的，您可以尝试通过如下操作启动它：
进入命令提示符或终端，输入“java -jar {kiftd主目录路径}{kiftd主程序名}”，然后回车执行。
例如，如果您的kiftd解压在“D:\kiftd\”中，主程序名称为“kiftd-1.0.26-RELEASE.jar”，那么应该在命令提示符中执行“java -jar D:\kiftd\kiftd-1.0.26-RELEASE.jar”，然后回车。
这样，您便可以指定操作系统使用正确的执行格式来启动kiftd程序了。
当然，如果您希望以后能够通过双击直接启动它，还可以将上述命令保存至文本文件中，然后将该文件的后缀改为.bat，这样便可以直接双击该文件来启动kiftd。

**Comment by KOHGYLW** [comment]
您的问题未收到进一步的回复，默认已解决，现关闭该issue。如果您希望得到更多帮助，欢迎提交新的issue。
