### ISSUE TITLE
您好，问下服务端机器是必须有公网IP吧？

### ISSUE THREAD

**Issue by xiaofeier312** [KOHGYLW/kiftd#72]
您好，问下服务端机器是必须有公网IP吧？我看用的时候需要用IP访问，想要在外网访问需要独立的IP是吧，谢谢

**Comment by KOHGYLW** [comment]
您好，如果您需要在公网访问，那么就需要确保kiftd服务器端能够接入公网。当然，除了直接使用公网IP外，也可以使用内网穿透，两者皆可。
