### ISSUE TITLE
在Linux中怎么使用？

### ISSUE THREAD

**Issue by jie12366** [KOHGYLW/kiftd#73]
在Linux启动有点问题，能不能提供一个教程？

**Comment by xiaofeier312** [comment]
我也想问下，您好，必须是有界面的操作系统才能用么，有没有命令行模式？linux服务器上没有页面啊

**Comment by jie12366** [comment]
我现在用的可道云，了解一下

**Comment by KOHGYLW** [comment]
@jie12366 @xiaofeier312 在Linux中也是可以直接使用命令操作的，完成部署后（安装JAVA、配置JAVA的环境变量、下载并解压kiftd），您可以直接使用命令模式启动kiftd并在无图形界面的环境下操作。具体内容可以参见《kiftd说明文档》中的“使用命令控制kiftd”（p54）一章。
