### ISSUE TITLE
单个账户对应单个文件系统

### ISSUE THREAD

**Issue by LKX787832305** [KOHGYLW/kiftd#75]
目前用户只需要登陆账户，便可以看到网盘里默认的文件，能否设置成一个账户对应一个文件夹，里面的文件和子文件夹不会被别的账户看到？

**Comment by KOHGYLW** [comment]
您好，很高兴收到您的建议！
这一建议在之前被其他用户提出过，因此本人也对该建议的可行性进行过研究。可惜的是，基于目前的系统设计结构，如果要加入这一功能从设计上看非常困难，且与kiftd的设计初衷相违背，因此这一建议最终未被采纳。
当然，kiftd官方目前也提供了对这一需求的现有解决方案——对于希望达到这一效果的用户，目前官方推荐的做法有两种：1，如果用户即需要存放自己的隐私文件，同时还需要与其他用户分享文件，那么可以将需要保护的文件放置在自己创建的“仅创建者“文件夹内以实现对这些文件的保护，非必须保护的文件则放置在公共位置下。2，如果用户仅希望存储文件而完全不需要分享，那么可以为这些用户单独部署一个kiftd服务器从而实现物理隔离，这样能够为用户提供最接近公共网盘服务的体验，不过管理起来相对繁琐。
以上，希望能够帮助到您。
