### ISSUE TITLE
未检测到https端口配置

### ISSUE THREAD

**Issue by x-66** [KOHGYLW/kiftd#76]
配置文件以修改，程序未检测到https端口配置
![2](https://user-images.githubusercontent.com/59433197/71656228-8c826200-2d75-11ea-816b-9e419ce4d810.png)
![11](https://user-images.githubusercontent.com/59433197/71656229-8d1af880-2d75-11ea-905e-e90291844d88.png)

**Comment by KOHGYLW** [comment]
是 https.port 而不是 https.prot……

**Comment by x-66** [comment]
谢谢解答！问题已解决
