### ISSUE TITLE
删除文件失败

### ISSUE THREAD

**Issue by inbjo** [KOHGYLW/kiftd#77]
上传了一个avi视频文件，然后点击播放打开了播放页面的网页 提示转码  然后正常播放了
关掉网页 无法删除该文件，估计是被转码程序占用没有释放。

**Comment by KOHGYLW** [comment]
您好，确实可能是由于该原因引起的。您可以稍后再试，或者重启服务器（从而令文件节点重新校对）。

**Comment by inbjo** [comment]
重启再次删除是成功的
