### ISSUE TITLE
建议增加更好的用户对文件夹权限的功能

### ISSUE THREAD

**Issue by dashi6174** [KOHGYLW/kiftd#79]
当前的权限管理不能满足如下的场景:
比如在根目录下有8个目录，分别是8个不同部门的目录；
要求部分用户可以对所有的8个目录有权限，而产品线的用户只能对单个产品目录有权限。

**Comment by KOHGYLW** [comment]
您好，如果您指的“有权限”是指有访问权限的话，那么您不妨试试这样：先由8个隶属于不同小组（例如小组“A”、"B"、“C”……“H”）的账户分别创建这8个目录，并将其设置为“仅小组”；之后，让部分可以访问所有8个目录的账户的小组都设置为这8个小组（即每个用户的小组都是“A;B;C...;H”），这样就能让这些用户同时访问全部8个文件夹了；而产品线的用户则可以单独设置小组（也就是说“A”、“B”、“C”……“H”中的一个），这样就只能访问单独的文件夹。
如果您不仅仅是希望控制账户的访问，还希望控制账户的操作权限，那么可以使用“为账户在特定文件夹设置额外权限”的方法单独设置每个账户、每个文件夹的操作权限，从而达到您希望的效果。
以上，推荐您按照上述方法进行尝试！

**Comment by KOHGYLW** [comment]
您好，由于一段时间内未收到您的进一步反馈，默认该问题已经解决。如果您还有其他疑问，欢迎提交新的issue！
