### ISSUE TITLE
导入文件的处理机制

### ISSUE THREAD

**Issue by wyongjian** [KOHGYLW/kiftd#80]
![image](https://user-images.githubusercontent.com/19405120/73451754-526fa480-43a3-11ea-84ee-e1009b07f87b.png)
在这里导入文件时是否可以直接链接到现有文件，而不是重新复制一份，太占空间了

**Comment by KOHGYLW** [comment]
这个实际上是由于kiftd自身的文件管理机制决定的，同时也是考虑到避免文件抢占的问题，所以还要维持当前的设计机制。
