### ISSUE TITLE
视频文件解码时间过长

### ISSUE THREAD

**Issue by ZHJ0125** [KOHGYLW/kiftd#81]
我测试的`100MB`的视频，解码时间超过**20分钟**。
`4MB`小视频的解码过程倒是挺快的。
请问有什么**加快解码速度**的方法吗？

**Comment by KOHGYLW** [comment]
视频解码确实是一个非常消耗CPU资源且耗时的操作——这一点应该是目前公认的。以kiftd所采用的技术来看（ffmpeg解码引擎），除了增加硬件的性能外，尚无较为明显的加快解码速度的方法，敬请谅解。
当然，您也可以选择将视频先在本地转码为MP4（AVC h.264编码）格式后再上传至网盘中，这样kiftd便能够直接播放它而无需在线解码了，大大减少解码时间并减轻服务器的CPU压力。

**Comment by ZHJ0125** [comment]
我将采用**本地转码**方式
谢谢！
