### ISSUE TITLE
无法下载？？？

### ISSUE THREAD

**Issue by ldou123** [KOHGYLW/kiftd#94]
![360截图20200424090652022](https://user-images.githubusercontent.com/64117916/80164233-02535780-860b-11ea-9261-f6bfa3d9ec13.jpg)
登陆了账号，重启了服务器，文件也是正常的，下载是用chronme、360浏览器也不行，IDM也是不行。是我的操作问题，还是我不小心把配置文件修改了？？？

**Comment by ldou123** [comment]
不好意思，好了

**Comment by KOHGYLW** [comment]
@ldou123 还是很高兴看到问题解决……那就关闭它了。
