### ISSUE TITLE
能否针对特定用户特定目录设置只能预览的权限？

### ISSUE THREAD

**Issue by boxiyang** [KOHGYLW/kiftd#99]
如题

**Comment by KOHGYLW** [comment]
很抱歉，但是无法实现。实际上，由于“预览”本质上就是“下载”，因此在技术上无法设定只允许用户预览而不能下载，这对于很多web资源网站都有效，例如视频、音乐等等，即使不显示“下载”按钮，掌握HTTP知识的用户依旧可以通过资源链接得到该资源——这并不复杂。因此，kiftd出于严谨考虑，将下载和预览统一为一个权限，就是希望使用者意识到：一个资源如果允许预览，那么用户就一定能下载它；如果一个资源不希望用户下载，那么最保险的做法是也不允许预览。
